# Generated by Django 3.1.3 on 2020-12-14 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agence de location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('label', models.CharField(max_length=30)),
                ('sample', models.CharField(max_length=30)),
                ('image', models.ImageField(max_length=300, null=True, upload_to='rental/photos')),
                ('description', models.TextField(null=True)),
                ('nb_seats', models.IntegerField(default=5)),
                ('nb_luggage', models.IntegerField(default=0)),
                ('nb_doors', models.IntegerField(default=5)),
                ('gear', models.CharField(choices=[('M', 'Manuelle'), ('A', 'Automatique'), ('MA', 'Manuelle ou automatique')], max_length=2)),
                ('energy', models.CharField(choices=[('G', 'Essence'), ('D', 'Diesel'), ('GD', 'Essence ou diesel'), ('E', 'Electrique'), ('H', 'Hybride')], max_length=2)),
                ('climate_control', models.BooleanField(default=True)),
                ('winter', models.BooleanField(default=False)),
                ('pre_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equivalent', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DrivingLicenceScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('number', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Fonctionnalités',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, null=True)),
                ('manufacturer_name', models.CharField(max_length=32)),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('engine_serial_number', models.CharField(max_length=255, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('motorisation', models.CharField(max_length=100, null=True)),
                ('code_motorisation', models.CharField(max_length=100, null=True)),
                ('couple', models.CharField(max_length=100, null=True)),
                ('puissance', models.CharField(max_length=100, null=True)),
                ('consommation', models.FloatField(default=0, null=True)),
                ('co2', models.IntegerField(default=0, null=True)),
                ('cx', models.CharField(max_length=100, null=True)),
                ('poids', models.CharField(max_length=100, null=True)),
                ('kilometrage', models.IntegerField(default=0, null=True)),
                ('boiteVitesse', models.CharField(max_length=100, null=True)),
                ('pneuDimension', models.CharField(max_length=100, null=True)),
                ('type_traction', models.CharField(max_length=100, null=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.agency')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.category')),
                ('features', models.ManyToManyField(to='rental.Feature')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'ordering': ['brand', 'manufacturer_name', 'registration'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('licence_scan', models.ImageField(blank=True, upload_to='customer-licences')),
                ('licence_number', models.CharField(max_length=12, null=True)),
                ('receiveAdds', models.BooleanField(default=True)),
                ('creditCardNumber', models.CharField(max_length=16, null=True)),
                ('creditCardValidity', models.CharField(max_length=4, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('scheduled_date_end', models.DateTimeField()),
                ('base_price', models.FloatField()),
                ('vat_rate', models.FloatField()),
                ('vat', models.FloatField()),
                ('total_price', models.FloatField()),
                ('remaining_price', models.FloatField()),
                ('fully_paid', models.BooleanField(default=False)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.agency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.vehicle')),
            ],
        ),
    ]
