# Generated by Django 3.1.2 on 2020-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agence de location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('label', models.CharField(max_length=30)),
                ('sample', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('nb_seats', models.IntegerField(default=5)),
                ('nb_luggage', models.IntegerField(default=0)),
                ('nb_doors', models.IntegerField(default=5)),
                ('gear', models.CharField(choices=[('M', 'Manuelle'), ('A', 'Automatique'), ('MA', 'Manuelle ou automatique')], max_length=2)),
                ('energy', models.CharField(choices=[('G', 'Essence'), ('D', 'Diesel'), ('GD', 'Essence ou diesel'), ('E', 'Electrique'), ('H', 'Hybride')], max_length=2)),
                ('climate_control', models.BooleanField(default=True)),
                ('winter', models.BooleanField(default=False)),
                ('pre_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equivalent', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'ordering': ['code'],
            },
        ),
    ]
