# Generated by Django 3.1.2 on 2020-12-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20201028_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Fonctionnalités',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=10, unique=True)),
                ('kilometrage', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_vehicules', to='rental.agency')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.category')),
            ],
        ),
    ]
