# Generated by Django 3.1.2 on 2020-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20201221_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='base_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remaining_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='scheduled_date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vat_rate',
            field=models.FloatField(null=True),
        ),
    ]
